# Generated by Django 5.0.6 on 2026-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('problem_slug', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=32)),
                ('source_code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('judged', 'Judged'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('judge0_tokens', models.JSONField(default=list)),
                ('verdict', models.CharField(blank=True, default='', max_length=32)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('forced', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'submissions',
                'indexes': [models.Index(fields=['state', 'submitted_at'], name='submissions_state_5e7dae_idx'), models.Index(fields=['session_id', '-submitted_at'], name='submissions_session_10aef1_idx')],
            },
        ),
    ]
