# Generated by Django 5.0.6 on 2026-05-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('statement_md', models.TextField(help_text='Markdown body shown to candidate.')),
                ('languages', models.JSONField(default=list, help_text='List of language slugs e.g. ["python", "javascript"]')),
                ('time_limit_ms', models.IntegerField(default=2000)),
                ('memory_limit_kb', models.IntegerField(default=262144)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True, default='')),
                ('expected_stdout', models.TextField()),
                ('is_example', models.BooleanField(default=False, help_text='If true, shown to the candidate in the problem statement.')),
                ('weight', models.IntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='interviewer.problem')),
            ],
            options={
                'db_table': 'testcases',
                'ordering': ['id'],
            },
        ),
    ]
