# Generated by Django 5.0.6 on 2026-05-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['difficulty', 'slug']},
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='statement_md_zh',
            field=models.TextField(blank=True, default='', help_text='Optional 繁中 markdown statement.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='title_zh',
            field=models.CharField(blank=True, default='', help_text='Optional traditional Chinese title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement_md',
            field=models.TextField(help_text='Markdown statement (English).'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(help_text='Canonical English title.', max_length=200),
        ),
    ]
