# Generated by Django 5.0.6 on 2026-05-19 13:00

import django.db.models.deletion
import web.apps.candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.CharField(default=web.apps.candidate.models._new_session_id, max_length=32, primary_key=True, serialize=False)),
                ('problem_slug', models.SlugField(max_length=128)),
                ('candidate_label', models.CharField(max_length=200)),
                ('interviewer_username', models.CharField(blank=True, default='', max_length=150)),
                ('duration_seconds', models.IntegerField()),
                ('deadline_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('frozen', 'Frozen'), ('reviewed', 'Reviewed')], default='pending', max_length=16)),
                ('reentries_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'deadline_utc'], name='interview_s_state_82cf7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReentryToken',
            fields=[
                ('token', models.CharField(default=web.apps.candidate.models._new_token, max_length=64, primary_key=True, serialize=False)),
                ('issued_by', models.CharField(max_length=150)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reentries', to='candidate.interviewsession')),
            ],
            options={
                'db_table': 'reentry_tokens',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(default=web.apps.candidate.models._new_token, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='candidate.interviewsession')),
            ],
            options={
                'db_table': 'admission_tokens',
            },
        ),
        migrations.CreateModel(
            name='CodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32)),
                ('source_code', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='candidate.interviewsession')),
            ],
            options={
                'db_table': 'code_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['session', '-captured_at'], name='code_snapsh_session_f31244_idx')],
            },
        ),
        migrations.CreateModel(
            name='AntiCheatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visibility_change', 'Visibility change'), ('blur', 'Blur (window/tab lost focus)'), ('paste', 'Paste'), ('copy', 'Copy'), ('tab_count', 'Tab-switch counter snapshot')], max_length=32)),
                ('byte_len', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticheat_events', to='candidate.interviewsession')),
            ],
            options={
                'db_table': 'anticheat_events',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['session', '-captured_at'], name='anticheat_e_session_a36fa1_idx')],
            },
        ),
    ]
